### ISSUE TITLE
How to change truncation value?

### ISSUE THREAD

**Issue by YukiSakuma** [HighCWu/anime_biggan_toy#1]
I've been eyeing the BigGAN anime model for a while but I don't have the know-how to get it work to generate images, so thanks so much for making it work! (if only BigGAN isn't  computationally expensive and complex to train and make it work :cry:)

Anyway so in BigGAN there is something called a truncation trick that is also in StyleGAN, where I could possibly change the truncation value in the code?

For reference I am using this: https://colab.research.google.com/github/HighCWu/anime_biggan_toy/blob/main/colab/Play_Anime_BigGAN.ipynb

**Comment by HighCWu** [comment]
As far as I know, truncation trick will reduce diversity and increase fidelity.  Because I made simple toys, I didn't apply this trick.  Instead, the ordinary standard normal distribution is used. 
I will consider adding that trick.

**Comment by YukiSakuma** [comment]
Thanks for considering!

**Comment by HighCWu** [comment]
I added `trunc_gen.py` for truncation trick. This result is not very good. I don't know if there is any problem with my operation. I directly refer to the `tranc z samples` in the pytorch version of BigGAN.
