### ISSUE TITLE
Is there a way to generate by class?

### ISSUE THREAD

**Issue by YukiSakuma** [HighCWu/anime_biggan_toy#2]
Correct me if I'm wrong but the model was trained on 1000 classes, is there a way to generate images by class number?
Like I want to generate images for 500th class for example, is there a lookup what anime character for the 500th class?

I know this one has it: https://www.gwern.net/Faces#constructing-d1k but that was trained on a different model and dataset (Danbooru2018-1K Dataset) so it is safe to say the classes are still the same on this one (DANBOORU2019+E621) ?

**Comment by HighCWu** [comment]
Shawwn trained the model using random classes, so there should be no clear corresponding class

**Comment by YukiSakuma** [comment]
I see so it's like trying to emulate unconditional BigGAN

**Comment by HighCWu** [comment]
Maybe it is. However, passing in different types seems to have some impact on the generated results. Some people suggest pre-training a clustering model and then training BigGAN by classification. Maybe it's a good idea. But for training, we may have to wait for Shawwn.
