### ISSUE TITLE
Such a great project! Is it possible to run with anaconda on Windows?

### ISSUE THREAD

**Issue by HelixNGC7293** [HighCWu/anime_biggan_toy#3]
项目超赞，已星！！本地运行需要的requirement都是啥呢，是不是要安装一个paddlepaddle 1.8.4环境之类的？
如果可以的话，我打算试试做一期视频介绍一下~

**Comment by HelixNGC7293** [comment]
本地运行起来啦~ 另外我用的是paddle2.0.0-rc0所以bmm从paddle.layers迁移到了paddle.tensor, 修改networks/model.py文件里bmm的引用就可以运行了~

**Comment by HighCWu** [comment]
谢谢关注。你也蛮有探索精神的，这么快改好2.0版本了😁

**Comment by HighCWu** [comment]
另外，如果你想安装在anaconda上应该很容易。现在paddle2.0还不太稳定，尽管我已经用它写了一个项目。实际上安装paddlepaddle-gpu==1.8.5可能是更好地选择，clone我的项目后，参考`Samples.ipynb`里的代码运行项目应该很容易，display图片的过程也可以改为save，我想那应该很轻松。
不过我倒不会因为环境而担忧，我转换模型的过程使用了colab，推理过程使用了ai studio，我的Readme里应该都有链接。即开即用，还有免费的GPU，何乐而不为呢😁

**Comment by HighCWu** [comment]
> 项目超赞，已星！！本地运行需要的requirement都是啥呢，是不是要安装一个paddlepaddle 1.8.4环境之类的？
> 如果可以的话，我打算试试做一期视频介绍一下~

很高兴你有兴趣介绍它一下。如果可能的话，在做视频的时候除了提到我的项目外，记得提及Gwern和Shawwn，他们花费了大量的时间改良BigGAN，我想我只是做了一点微不足道的贡献。

**Comment by HelixNGC7293** [comment]
了解！感谢！Anaconda+JupyterLab已经搭好啦！~好嘞Gwern和Shawwn我到时也介绍介绍
